In [13]:
import numpy as np


x = np.zeros((10,))
x = np.array([[1, 2, 3, 4, 5, 0, 1, 1, 1], [1, 2, 3, 4, 5, 0, 1, 1, 1]])
x.shape
row, column = x.shape
print(row)
print(column)




2
9


In [27]:
# Convert elements of the `y` array to `1`s
def g(y):
    return np.ones(y.shape)


arr1 = np.array([[1, 2, 3], [3, 2, 1]])
g(arr1)


y = np.array([[1, 2, 3], [3, 2, 1]])
y + 10





array([[11, 12, 13],
       [13, 12, 11]])

In [19]:
def f(y):
    k = 1.7e-3
    return y*(1-y/k)

y1 = np.array([[1, 2, 3], [3, 2, 1]])
print(y1 / 1.7e-3)
y2 = g(y1)
fy1 = f(y1)
fy2 = f(y2)

print("fy1")
print(fy1)
print("fy2")
print(fy2)

[[ 588.23529412 1176.47058824 1764.70588235]
 [1764.70588235 1176.47058824  588.23529412]]
fy1
[[ -587.23529412 -2350.94117647 -5291.11764706]
 [-5291.11764706 -2350.94117647  -587.23529412]]
fy2
[[-587.23529412 -587.23529412 -587.23529412]
 [-587.23529412 -587.23529412 -587.23529412]]


In [1]:
import numpy as np
from numpy import linalg as LA
import scipy.sparse as sparse
from scipy.sparse import csc_matrix
from scipy.sparse import dia_matrix
import itertools
import operator
import pdb
import math
from tqdm import tqdm
#import surface_fitter as sf

from sklearn.neighbors import NearestNeighbors

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter


def Lasso(X0, Y, lam, w = np.array([0]), maxit = 100, normalize = 2):
    """
    Uses accelerated proximal gradient (FISTA) to solve Lasso
    argmin (1/2)*||Xw-Y||_2^2 + lam||w||_1
    """
    
    # Obtain size of X
    n,d = X0.shape
    X = np.zeros((n,d), dtype=np.complex64)
    Y = Y.reshape(n,1)
    
    # Create w if none is given
    if w.size != d:
        w = np.zeros((d,1), dtype=np.complex64)
    w_old = np.zeros((d,1), dtype=np.complex64)
        
    # Initialize a few other parameters
    converge = 0
    objective = np.zeros((maxit,1))
    
    # First normalize data
    if normalize != 0:
        Mreg = np.zeros((d,1))
        for i in range(0,d):
            Mreg[i] = 1.0/(np.linalg.norm(X0[:,i],normalize))
            X[:,i] = Mreg[i]*X0[:,i]
    else: X = X0

    # Lipschitz constant of gradient of smooth part of loss function
    L = np.linalg.norm(X.T.dot(X),2)
    
    # Now loop until converged or max iterations
    for iters in range(0, maxit):
         
        z = w + iters/float(iters+1)*(w - w_old)
        
        w_old = np.copy(w)

        z = z - X.T.dot(X.dot(z)-Y)/L
        for j in range(d): w[j] = np.multiply(np.sign(z[j]), np.max([abs(z[j])-lam/L,0]))

        # Could put in some sort of break condition based on convergence here.
        if np.linalg.norm(w-w_old) < 1e-2:break


    # Now that we have the sparsity pattern, used least squares.
    biginds = np.where(w != 0)[0]
    if biginds != []: w[biginds] = np.linalg.lstsq(X[:, biginds],Y,rcond=-1)[0]

    # Finally, reverse the regularization so as to be able to use with raw data
    if normalize != 0: return np.multiply(Mreg,w)
    else: return w

ModuleNotFoundError: No module named 'scipy'

In [2]:
# AMSSIMONS_ABM_sim_rp_0.5_rd_0.05_real1.npy
import numpy as np

# Load the data from the .npy file
data = np.load('AMSSIMONS_ABM_sim_rp_0.5_rd_0.05_real1.npy', allow_pickle=True)

# Print the data
print(data)

{'inputs': array([[ 0.        ],
       [ 0.1010101 ],
       [ 0.2020202 ],
       [ 0.3030303 ],
       [ 0.4040404 ],
       [ 0.50505051],
       [ 0.60606061],
       [ 0.70707071],
       [ 0.80808081],
       [ 0.90909091],
       [ 1.01010101],
       [ 1.11111111],
       [ 1.21212121],
       [ 1.31313131],
       [ 1.41414141],
       [ 1.51515152],
       [ 1.61616162],
       [ 1.71717172],
       [ 1.81818182],
       [ 1.91919192],
       [ 2.02020202],
       [ 2.12121212],
       [ 2.22222222],
       [ 2.32323232],
       [ 2.42424242],
       [ 2.52525253],
       [ 2.62626263],
       [ 2.72727273],
       [ 2.82828283],
       [ 2.92929293],
       [ 3.03030303],
       [ 3.13131313],
       [ 3.23232323],
       [ 3.33333333],
       [ 3.43434343],
       [ 3.53535354],
       [ 3.63636364],
       [ 3.73737374],
       [ 3.83838384],
       [ 3.93939394],
       [ 4.04040404],
       [ 4.14141414],
       [ 4.24242424],
       [ 4.34343434],
       [ 4.44444444],